apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test-ci
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      nodeSelector:
        QA: "TRUE"
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 120