@Library('jenkins-shared-library') _

evenOrOdd(currentBuild.getNumber())

/*myDeliveryPipeline {
  name = "Alejandro"
}*/
         
 //pipelineStandard1 {
 //        nombre= 'Sofia'
// }

/*evenOrOdd{
   numeroEjecucion = currentBuild.getNumber()      
}*/


