@Library('jenkins-shared-library') _

//evenOrOdd(currentBuild.getNumber())

myDeliveryPipeline {
  name = "cargaMasiva"
}
         
 //pipelineStandard1 {
 //        nombre= 'Sofia'
// }

/*evenOrOdd{
   numeroEjecucion = currentBuild.getNumber()      
}*/


